/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as IndexOtherImport } from './routes/index.other'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IndexOtherRoute = IndexOtherImport.update({
  id: '/index/other',
  path: '/index/other',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/index/other': {
      id: '/index/other'
      path: '/index/other'
      fullPath: '/index/other'
      preLoaderRoute: typeof IndexOtherImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/index/other': typeof IndexOtherRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/index/other': typeof IndexOtherRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/index/other': typeof IndexOtherRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/index/other'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/index/other'
  id: '__root__' | '/' | '/index/other'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexOtherRoute: typeof IndexOtherRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexOtherRoute: IndexOtherRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/index/other"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/index/other": {
      "filePath": "index.other.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
